### ISSUE TITLE
catkin_make hangs after -- BUILD_SHARED_LIBS is on 

### ISSUE THREAD

**Issue by ninjapc90** [ros/catkin#1085]
I have insalled ROS melodic on Ubuntu 18.04. I abruptly  started facing this issue. When I run `catkin_make` the system hangs on `BUILD_SHARED_LIBS is on`. This command was working perfectly earlier.  I have also tried removing build and devel directories and running `catkin_make`.
The catkin workspace was made following the tutorial on ROS wiki - http://wiki.ros.org/catkin/Tutorials/create_a_workspace

```
$ source /opt/ros/melodic/setup.bash
$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws/
$ catkin_make
```

Here is the console output - 

```
pooja:~/catkin_ws$ catkin_make
Base path: /home/pooja/catkin_ws
Source space: /home/pooja/catkin_ws/src
Build space: /home/pooja/catkin_ws/build
Devel space: /home/pooja/catkin_ws/devel
Install space: /home/pooja/catkin_ws/install
####
#### Running command: "cmake /home/pooja/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/pooja/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/pooja/catkin_ws/install -G Unix Makefiles" in "/home/pooja/catkin_ws/build"
####
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/pooja/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pooja/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
```
On stopping the process following message is generated

```
^CTraceback (most recent call last):
  File "/opt/ros/melodic/bin/catkin_make", line 306, in <module>
    sys.exit(main())
  File "/opt/ros/melodic/bin/catkin_make", line 209, in main
    run_command_colorized(cmd, build_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/builder.py", line 189, in run_command_colorized
    run_command(cmd, cwd, quiet=quiet, colorize=True, add_env=add_env)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/builder.py", line 211, in run_command
    line = proc.stdout.readline()
KeyboardInterrupt
```

I list the packages with` rospack list-names`. All package names start with lower case. 

```
~/Desktop/catkin_ws/src$ rospack list-names
actionlib
actionlib_msgs
actionlib_tutorials
aerial_global_planner
aerial_local_planner
angles
ar_helipad
ar_track_alvar
ar_track_alvar_msgs
bebop_gazebo
bond
bondcpp
bondpy
camera_calibration
camera_calibration_parsers
camera_info_manager
catkin
chomp_motion_planner
class_loader
cmake_modules
compressed_depth_image_transport
compressed_image_transport
control_msgs
control_toolbox
controller_interface
controller_manager
controller_manager_msgs
cpp_common
cv_bridge
depth_image_proc
diagnostic_aggregator
diagnostic_analysis
diagnostic_common_diagnostics
diagnostic_msgs
diagnostic_updater
diff_drive_controller
dynamic_reconfigure
eigen_conversions
eigen_stl_containers
eigenpy
filters
forward_command_controller
gazebo_dev
gazebo_msgs
gazebo_plugins
gazebo_ros
gazebo_ros_control
gencpp
geneus
genlisp
genmsg
gennodejs
genpy
geographic_msgs
geometric_shapes
geometry_msgs
gl_dependency
hardware_interface
hector_compressed_map_transport
hector_gazebo_plugins
hector_gazebo_thermal_camera
hector_gazebo_worlds
hector_geotiff
hector_geotiff_plugins
hector_imu_attitude_to_tf
hector_imu_tools
hector_map_server
hector_map_tools
hector_mapping
hector_marker_drawing
hector_nav_msgs
hector_pose_estimation
hector_pose_estimation_core
hector_quadrotor
hector_quadrotor_actions
hector_quadrotor_controller_gazebo
hector_quadrotor_controllers
hector_quadrotor_demo
hector_quadrotor_description
hector_quadrotor_gazebo
hector_quadrotor_gazebo_plugins
hector_quadrotor_interface
hector_quadrotor_model
hector_quadrotor_pose_estimation
hector_quadrotor_teleop
hector_sensors_description
hector_sensors_gazebo
hector_slam_launch
hector_trajectory_server
hector_uav_msgs
image_geometry
image_proc
image_publisher
image_rotate
image_transport
image_view
interactive_marker_tutorials
interactive_markers
joint_limits_interface
joint_state_controller
joint_state_publisher
joy
kdl_conversions
kdl_parser
kdl_parser_py
laser_assembler
laser_filters
laser_geometry
librviz_tutorial
map_msgs
media_export
message_filters
message_generation
message_runtime
message_to_tf
mk
move_base_msgs
moveit_commander
moveit_core
moveit_fake_controller_manager
moveit_kinematics
moveit_msgs
moveit_planners_chomp
moveit_planners_ompl
moveit_ros_benchmarks
moveit_ros_control_interface
moveit_ros_manipulation
moveit_ros_move_group
moveit_ros_perception
moveit_ros_planning
moveit_ros_planning_interface
moveit_ros_robot_interaction
moveit_ros_visualization
moveit_ros_warehouse
moveit_setup_assistant
moveit_simple_controller_manager
nav_msgs
nodelet
nodelet_topic_tools
nodelet_tutorial_math
object_recognition_msgs
octomap
octomap_msgs
ompl
orocos_kdl
pcl_conversions
pcl_msgs
pcl_ros
pluginlib
pluginlib_tutorials
polled_camera
position_controllers
python_orocos_kdl
python_qt_binding
qt_dotgraph
qt_gui
qt_gui_cpp
qt_gui_py_common
qwt_dependency
random_numbers
realtime_tools
resource_retriever
robot_state_publisher
ros_environment
rosbag
rosbag_migration_rule
rosbag_storage
rosbash
rosboost_cfg
rosbuild
rosclean
rosconsole
rosconsole_bridge
roscpp
roscpp_serialization
roscpp_traits
roscpp_tutorials
roscreate
rosgraph
rosgraph_msgs
roslang
roslaunch
roslib
roslint
roslisp
roslz4
rosmake
rosmaster
rosmsg
rosnode
rosout
rospack
rosparam
rospy
rospy_tutorials
rosservice
rostest
rostime
rostopic
rosunit
roswtf
rqt_action
rqt_bag
rqt_bag_plugins
rqt_console
rqt_dep
rqt_graph
rqt_gui
rqt_gui_cpp
rqt_gui_py
rqt_image_view
rqt_launch
rqt_logger_level
rqt_moveit
rqt_msg
rqt_nav_view
rqt_plot
rqt_pose_view
rqt_publisher
rqt_py_common
rqt_py_console
rqt_reconfigure
rqt_robot_dashboard
rqt_robot_monitor
rqt_robot_steering
rqt_runtime_monitor
rqt_rviz
rqt_service_caller
rqt_shell
rqt_srv
rqt_tf_tree
rqt_top
rqt_topic
rqt_web
rviz
rviz_plugin_tutorials
rviz_python_tutorial
self_test
sensor_msgs
shape_msgs
smach
smach_msgs
smach_ros
smclib
srdfdom
stage
stage_ros
std_msgs
std_srvs
stereo_image_proc
stereo_msgs
teleop_twist_keyboard
tf
tf2
tf2_eigen
tf2_geometry_msgs
tf2_kdl
tf2_msgs
tf2_py
tf2_ros
tf2_sensor_msgs
tf_conversions
tf_velocity_estimator
theora_image_transport
topic_tools
trajectory_msgs
transmission_interface
turtle_actionlib
turtle_tf
turtle_tf2
turtlesim
twist_mux
twist_mux_msgs
uav_landing
urdf
urdf_parser_plugin
urdf_sim_tutorial
urdf_tutorial
urdfdom_py
uuid_msgs
visualization_marker_tutorials
visualization_msgs
warehouse_ros
webkit_dependency
xacro
xmlrpcpp
```

```
~/Desktop/catkin_ws/src$ echo $ROS_PACKAGE_PATH
/home/pooja/Desktop/catkin_ws/src:/opt/ros/melodic/share
```

**Comment by dirk-thomas** [comment]
Can you please share the content of your workspace under `src`.

**Comment by dirk-thomas** [comment]
Closing due to no response.
