### ISSUE TITLE
catkin_make and catkin_make clean does not work - bad variable name

### ISSUE THREAD

**Issue by wooriel** [ros/catkin#1115]
I downloaded Ubuntu 18.04LTS, WSL, and ros-melodic on my computer.
Then, I tried to create a workspace. But catkin_make does not even work.
Build used to work, but once it gets errors after I change CMakeLists.txt, it showed the same error.
I thought the problem was because of the python version, but I am not certain at this point.
catkin_make clean doesn't even work for me.
The error starts when going through files on C/Program Files/
I am not sure if it is relevant to environment variables, but please help...

These are my environment variables and other path variables:
PYTHONPATH=/opt/ros/melodic/lib/python2.7/dist-packages
ROS_PACKAGE_PATH=/opt/ros/melodic/share
ARCHDIR=Linux64
ROSLISP_PACKAGE_DIRECTORIES=
LOGNAME=wooriel
PATH=/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/woogy/AppData/Local/Programs/Python/Python36/Scripts:/mnt/c/Program Files/Haskell/bin:/mnt/c/Program Files/Haskell Platform/8.0.2-a/lib/extralibs/bin:/mnt/c/Program Files/Haskell Platform/8.0.2-a/bin:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Brackets/command:/mnt/c/Program Files (x86)/GtkSharp/2.12/bin:/mnt/c/Program Files/Haskell Platform/8.0.2-a/mingw/bin:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/SMLNJ/bin/:/mnt/c/Users/woogy/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/XSB/config/x86-pc-windows/bin/:/mnt/c/Users/woogy/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Python 3.6:/mnt/c/Users/woogy/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/woogy/AppData/Local/Programs/Python/Python36:/mnt/c/Users/woogy/AppData/Local/Programs/Python/Python36/Scripts:/mnt/c/Program Files/emacs-26.3-x86_64/bin:/snap/bin
PKG_CONFIG_PATH=/opt/ros/melodic/lib/pkgconfig
WSLENV=
ROS_DISTRO=melodic
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env
wooriel@DESKTOP-S2934ST:/mnt/c/retina_analyzer_ros/catkin_ws$ exit
logout

HOSTTYPE=x86_64
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=C.UTF-8
ROS_ETC_DIR=/opt/ros/melodic/etc/ros
WSL_DISTRO_NAME=Ubuntu-18.04
USER=wooriel
PWD=/mnt/c/Users/woogy
HOME=/home/wooriel
EUSDIR=/opt/ros/melodic/share/euslisp/jskeus/eus/
CMAKE_PREFIX_PATH=/opt/ros/melodic
NAME=DESKTOP-S2934ST
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
ROS_ROOT=/opt/ros/melodic/share/ros
ROS_MASTER_URI=http://localhost:11311
ROS_VERSION=1
SHELL=/bin/bash
TERM=xterm-256color
ROS_PYTHON_VERSION=2
SHLVL=1
PYTHONPATH=/opt/ros/melodic/lib/python2.7/dist-packages
ROS_PACKAGE_PATH=/opt/ros/melodic/share
ARCHDIR=Linux64
ROSLISP_PACKAGE_DIRECTORIES=
LOGNAME=wooriel
PATH=/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/bin:/opt/ros/melodic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/woogy/AppData/Local/Programs/Python/Python36/Scripts:/mnt/c/Program Files/Haskell/bin:/mnt/c/Program Files/Haskell Platform/8.0.2-a/lib/extralibs/bin:/mnt/c/Program Files/Haskell Platform/8.0.2-a/bin:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Brackets/command:/mnt/c/Program Files (x86)/GtkSharp/2.12/bin:/mnt/c/Program Files/Haskell Platform/8.0.2-a/mingw/bin:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/SMLNJ/bin/:/mnt/c/Users/woogy/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/XSB/config/x86-pc-windows/bin/:/mnt/c/Users/woogy/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Python 3.6:/mnt/c/Users/woogy/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/woogy/AppData/Local/Programs/Python/Python36:/mnt/c/Users/woogy/AppData/Local/Programs/Python/Python36/Scripts:/mnt/c/Program Files/emacs-26.3-x86_64/bin:/snap/bin
PKG_CONFIG_PATH=/opt/ros/melodic/lib/pkgconfig
WSLENV=
ROS_DISTRO=melodic
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env

Below is the error code:
wooriel@DESKTOP-S2934ST:/mnt/c/retina_analyzer_ros/catkin_ws$ catkin_make                                                                     Base path: /mnt/c/retina_analyzer_ros/catkin_ws                        
Source space: /mnt/c/retina_analyzer_ros/catkin_ws/src                 
Build space: /mnt/c/retina_analyzer_ros/catkin_ws/build                
Devel space: /mnt/c/retina_analyzer_ros/catkin_ws/devel                
Install space: /mnt/c/retina_analyzer_ros/catkin_ws/install            
#### Running command: "cmake /mnt/c/retina_analyzer_ros/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/mnt/c/retina_analyzer_ros/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/mnt/c/retina_analyzer_ros/catkin_ws/install -G Unix Makefiles" in "/mnt/c/retina_analyzer_ros/catkin_ws/build"               ####                                                                   -- Using CATKIN_DEVEL_PREFIX: /mnt/c/retina_analyzer_ros/catkin_ws/devel                                                                      -- Using CMAKE_PREFIX_PATH: /opt/ros/melodic                           
-- This workspace overlays: /opt/ros/melodic                           
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2")                                            
-- Using PYTHON_EXECUTABLE: /usr/bin/python2                           
-- Using Debian Python package layout                                  
-- Using empy: /usr/bin/empy                                           
-- Using CATKIN_ENABLE_TESTING: ON                                     
-- Call enable_testing()                                               
-- Using CATKIN_TEST_RESULTS_DIR: /mnt/c/retina_analyzer_ros/catkin_ws/build/test_results                                                     -- Found gtest sources under '/usr/src/googletest': gtests will be built                                                                      -- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17")       
-- Using Python nosetests: /usr/bin/nosetests-2.7                      
-- catkin 0.7.26                                                       
-- BUILD_SHARED_LIBS is on                                             /mnt/c/retina_analyzer_ros/catkin_ws/devel/env.sh: 4: export: Files/Haskell/bin:/mnt/c/Program: bad variable name                             Traceback (most recent call last):                                       
File "/mnt/c/retina_analyzer_ros/catkin_ws/build/catkin_generated/generate_cached_setup.py", line 22, in <module>                          
code = generate_environment_script('/mnt/c/retina_analyzer_ros/catkin_ws/devel/env.sh')                                             File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/environment_cache.py", line 62, in generate_environment_script                 
output = subprocess.check_output([env_script, sys.executable, '-c', python_code])                                                  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
raise CalledProcessError(retcode, cmd, output=output)              subprocess.CalledProcessError: Command '['/mnt/c/retina_analyzer_ros/catkin_ws/devel/env.sh', '/usr/bin/python2', '-c', 'import os; print(dict(os.environ))']' returned non-zero exit status 2                       CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):                                                     execute_process(/usr/bin/python2                                       "/mnt/c/retina_analyzer_ros/catkin_ws/build/catkin_generated/generate_cached_setup.py")                                                       
returned error code 1                                                
Call Stack (most recent call first):                                     /opt/ros/melodic/share/catkin/cmake/all.cmake:208 (safe_execute_process)                                                                      /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)    CMakeLists.txt:56 (find_package)                                                                                                                                                                                   

-- Configuring incomplete, errors occurred!                            
See also "/mnt/c/retina_analyzer_ros/catkin_ws/build/CMakeFiles/CMakeOutput.log".                                                             See also "/mnt/c/retina_analyzer_ros/catkin_ws/build/CMakeFiles/CMakeError.log".                                                              Invoking "cmake" failed

**Comment by wooriel** [comment]
I think this is due to a PATH. It called win10 environment path on WSL and there was a spaces between $PATH variable.
I solved it by changing .bashrc file:
>> nano ~/.bashrc
Add this line at the end of the bashrc file:
>>PATH=$(/usr/bin/printenv PATH | /usr/bin/perl -ne 'print join(":", grep { !/\/mnt\/[a-z]/ } split(/:/));')

Reference : https://stackoverflow.com/questions/51336147/how-to-remove-the-win10s-path-from-wsl
