### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 19725: invalid continuation byte

### ISSUE THREAD

**Issue by karthiknit1** [ros/catkin#1184]
When a catkin build is done on any ROS package in a English windows machine with ROS Noetic distribution with any environment variable value having a non-ASCII character , it leads to the following build error:

Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Temp\T kCM\tp47a9facc_1ee3_4ccd_9f84_5b5a2313db56\build\catkin_generated\generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('C:/Users/XXXXX/AppData/Local/Temp/T kCM/tp47a9facc_1ee3_4ccd_9f84_5b5a2313db56/devel/env.bat')
  File "C:\Users\XXXXX\AppData\Local\Temp\TkCM\ml_pz84\WS6813~1\ros1\lib\site-packages\catkin\environment_cache.py", line 63, in generate_environment_script
    env_after = ast.literal_eval(output.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 19725: invalid continuation byte
CMake Error at C:/Users/XXXXX/AppData/Local/Temp/TkCM/ml_pz84/w s/ros1/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  
execute_process(C:/Users/XXXXX/AppData/Local/Temp/tp23c905ed_08b6_4476_894e_cc6222a162d9/ros1/win64/venv/Scripts/python.exe
  "C:/Users/XXXXX/AppData/Local/Temp/T
  kCM/tp47a9facc_1ee3_4ccd_9f84_5b5a2313db56/build/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):

Expected Behavior:
Build should be successful

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
