### ISSUE TITLE
test_basics only works with natty

### ISSUE THREAD

**Issue by mkjaergaard** [ros/catkin#16]
from a lucid system:
[/home/local/catkin_test/catkin/test]$ nosetests  

```
FAIL: test_basics.test_tiny
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/nose-1.1.2-py2.6.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/local/catkin_test/catkin/test/test_basics.py", line 45, in test_tiny
    "catkin-test-nolangs_3.4.5~natty_source.changes")
  File "/home/local/catkin_test/catkin/test/catkintest/__init__.py", line 89, in assert_exists
    assert exists(p), "%s doesn't exist" % p
AssertionError: /home/local/catkin_test/catkin/test/src/catkin-test-nolangs_3.4.5~natty.dsc doesn't exist
    '/home/local/catkin_test/catkin/test/src/catkin-test-nolangs_3.4.5~natty.dsc' = <module 'os' from '/usr/lib/python2.6/os.pyc'>.path.join('/home/local/catkin_test/catkin/test/src', 'catkin-test-nolangs_3.4.5~natty.dsc')
    print "Checking for", '/home/local/catkin_test/catkin/test/src/catkin-test-nolangs_3.4.5~natty.dsc'
>>  assert exists('/home/local/catkin_test/catkin/test/src/catkin-test-nolangs_3.4.5~natty.dsc'), "%s doesn't exist" % '/home/local/catkin_test/catkin/test/src/catkin-test-nolangs_3.4.5~natty.dsc'
```

**Comment by straszheim** [comment]
yup that did it:

Ran 4 tests in 129.175s
