### ISSUE TITLE
Broken unicode support for maintainer field in package.xml

### ISSUE THREAD

**Issue by roehling** [ros/catkin#342]
Using non-ascii characters in the maintainer field causes the following python error:

```
Traceback (most recent call last):
  File "/opt/ros/groovy/share/catkin/cmake/parse_package_xml.py", line 87, in <module>
    main()
  File "/opt/ros/groovy/share/catkin/cmake/parse_package_xml.py", line 81, in main
    lines = _get_output(package)
  File "/opt/ros/groovy/share/catkin/cmake/parse_package_xml.py", line 55, in _get_output
    values['MAINTAINER'] = '"%s"' % (', '.join([str(m) for m in package.maintainers]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 6: ordinal not in range(128)
```

Catkin 0.5.63 on Ubuntu Quantal

**Comment by roehling** [comment]
The problem has been resolved by commit ros-infrastructure/catkin_pkg@eca2dee05e26fc750a5a58f490e97548e25c7bb2
