### ISSUE TITLE
build can pull code from old install

### ISSUE THREAD

**Issue by gerkey** [ros/catkin#56]
This build: http://hudson:8080/job/catkin-dry-on-wet.fat.oneiric.amd64/27/console
has this error:
    [  6%] Generating Orocos Typelib XML code from std_msgs/Bool.msg
    Traceback (most recent call last):
      File "/home/jenkins/workspace/catkin-dry-on-wet.fat.oneiric.amd64/install/bin/gen_typelibxml.py", line 4, in <module>
        import pkg_resources
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2672, in <module>
        working_set.require(**requires**)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 654, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 552, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: gentypelibxml==0.0.2
    make[2]: **\* [gen/typelibxml/std_msgs/Bool.xml] Error 1
    make[1]: **\* [std_msgs/CMakeFiles/std_msgs_gentypelibxml.dir/all] Error 2
    make: **\* [all] Error 2

The source dir is /home/jenkins/workspace/catkin-dry-on-wet.fat.oneiric.amd64/src, the build dir is /home/jenkins/workspace/catkin-dry-on-wet.fat.oneiric.amd64/build, and the install dir is /home/jenkins/workspace/catkin-dry-on-wet.fat.oneiric.amd64/install.  Looks like the build is failing with an error in the previously installed code.

**Comment by gerkey** [comment]
Seems like, after having installed, something in the build toolchain is putting the install tree into PYTHONPATH.

**Comment by gerkey** [comment]
We tried and failed to reproduce this problem.  Perhaps it's been fixed.  Reopen if not.
