### ISSUE TITLE
Error when using new catkin with old catkin-pkg

### ISSUE THREAD

**Issue by scpeters** [ros/catkin#627]
I was getting the following error when using catkin cloned from source (b4f804db9e1d5b78976dbb9f59c5af39a02b04f6) with an old version of catkin-pkg (0.1.27):

```
Traceback (most recent call last):
  File "./src/catkin/bin/catkin_make_isolated", line 136, in <module>
    main()
  File "./src/catkin/bin/catkin_make_isolated", line 132, in main
    destdir=destdir
  File "./src/catkin/bin/../python/catkin/builder.py", line 756, in build_workspace_isolated
    packages = find_packages(sourcespace, exclude_subspaces=True)
  File "/Library/Python/2.7/site-packages/catkin_pkg/packages.py", line 87, in find_packages
    package = parse_package(os.path.join(basepath, path))
  File "/Library/Python/2.7/site-packages/catkin_pkg/package.py", line 317, in parse_package
    return parse_package_string(f.read(), filename)
  File "/Library/Python/2.7/site-packages/catkin_pkg/package.py", line 450, in parse_package_string
    raise InvalidPackage('Error(s) in %s:%s' % (filename, ''.join(['\n- %s' % e for e in errors])))
catkin_pkg.package.InvalidPackage: Invalid package manifest "/Users/scpeters/ws/gazebo/src/catkin/package.xml": Error(s) in /Users/scpeters/ws/gazebo/src/catkin/package.xml:
- The manifest must not contain the following tags: depend, build_export_depend, buildtool_export_depend
```

Updating to catkin-pkg version 0.2.2 solved the problem.

I'm reporting this in case someone else has the same problem.

**Comment by amineHorseman** [comment]
I had the same error and solved it using:

`pip install -U rosdep rosinstall_generator wstool rosinstall six vcstools setuptools`

In case the previous solution doesn't work.

**Comment by dirk-thomas** [comment]
@amineHorseman to avoid others to blindly copy-n-paste your approach: you should only install ROS Python packages using `pip` on systems which don't have Debian packages. On Debian systems you should use `apt` to update the installed binary packages.
