### ISSUE TITLE
catkin_make_isolated crashes if first package doesn't create devel dir

### ISSUE THREAD

**Issue by tfoote** [ros/catkin#665]
```
tecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tfoote/work/indigo/workspaces/rosconsole/build_isolated/console_bridge/devel
==> make -j8 -l8 in '/home/tfoote/work/indigo/workspaces/rosconsole/build_isolated/console_bridge/devel'
==> make install in '/home/tfoote/work/indigo/workspaces/rosconsole/build_isolated/console_bridge/devel'
Install the project...
-- Install configuration: ""
Phony install target
==> Generating an env.sh
Unhandled exception of type 'OSError':
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/builder.py", line 875, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/builder.py", line 641, in build_package
    destdir=destdir
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/builder.py", line 521, in build_cmake_package
    os.mkdir(os.path.dirname(new_env_path))
OSError: [Errno 2] No such file or directory: '/home/tfoote/work/indigo/workspaces/rosconsole/devel_isolated/console_bridge'
<== Failed to process package 'console_bridge': 
  [Errno 2] No such file or directory: '/home/tfoote/work/indigo/workspaces/rosconsole/devel_isolated/console_bridge'
Command failed, exiting.
tfoote@yeti:~/work/indigo/workspaces/rosconsole$ ls 
build_isolated  src
tfoote@yeti:~/work/indigo/workspaces/rosconsole$ mkdir -p devel_isolated/console_bridge
tfoote@yeti:~/work/indigo/workspaces/rosconsole$ catkin_make_isolated 
Base path: /home/tfoote/work/indigo/workspaces/rosconsole
Source space: /home/tfoote/work/indigo/workspaces/rosconsole/src
Build space: /home/tfoote/work/indigo/workspaces/rosconsole/build_isolated
Devel space: /home/tfoote/work/indigo/workspaces/rosconsole/devel_isolated
Install space: /home/tfoote/work/indigo/workspaces/rosconsole/install_isolated
```

~~  traversing 10 packages in topological order:
~~  - console_bridge (plain cmake)
~~  - joint_state_publisher
~~  - resource_retriever
~~  - robot_model
~~  - rosconsole_bridge
~~  - urdf_parser_plugin
~~  - collada_parser
~~  - urdf
~~  - collada_urdf
~~  - kdl_parser

```

==> Processing plain cmake package: 'console_bridge'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/tfoote/work/indigo/workspaces/rosconsole/build_isolated/console_bridge/devel'
==> make -j8 -l8 in '/home/tfoote/work/indigo/workspaces/rosconsole/build_isolated/console_bridge/devel'
==> make install in '/home/tfoote/work/indigo/workspaces/rosconsole/build_isolated/console_bridge/devel'
Install the project...
-- Install configuration: ""
Phony install target
==> Generating an env.sh
<== Finished processing package [1 of 10]: 'console_bridge'

```

**Comment by wjwwood** [comment]
Ah, we should probably switch the shim package's build type to cmake, which would solve this.

We do naively assume that all catkin packages will create a devel space.

**Comment by tfoote** [comment]
The shim packages are pure cmake and are flagged as such.

**Comment by dirk-thomas** [comment]
The reason is that the package does not actually install any file.
