### ISSUE TITLE
Allow verbose nosetest output

### ISSUE THREAD

**Issue by jpanikulam** [ros/catkin#759]
When running a conventional nosetest, i.e. nosetest -vv, we get verbose output

```
test_add_alarm (__main__.TestROSTools)
Ensure that adding an alarm succeeds without errors ... ok
test_get_image_msg (__main__.TestROSTools)
Test that a made ros image can be returned to its original form ... ok
test_instantiate_alarm_broadcaster (__main__.TestROSTools)
Ensure that the alarm broadcaster instantiates without errors ... ok
test_make_image_msg (__main__.TestROSTools)
Test that make ros image message doesn't fail ... ok
test_make_rotation (__main__.TestROSTools)
Test several random vector pairs, and see if we can generate a valid alignment ... ok
test_normalize_vector (__main__.TestROSTools)
Test vector normalization ... ok
test_rosmsg_to_numpy_custom (__main__.TestROSTools)
======================================================================
FAIL: test_rosmsg_to_numpy_quaternion (__main__.TestROSTools)
Test a rosmsg conversion for a geometry_msgs/Quaternion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jacob/repos/rosboat_ws/src/Sub8/utils/sub8_ros_tools/test_ros_tools/test_ros_tools.py", line 24, in test_rosmsg_to_numpy_quaternion
    self.assertFalse(True)
AssertionError: True is not false
----------------------------------------------------------------------
```

catkin_make run_tests only produces the non-verbose version:

```
.......F...
======================================================================
FAIL: Test a rosmsg conversion for a geometry_msgs/Quaternion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jacob/repos/rosboat_ws/src/Sub8/utils/sub8_ros_tools/test_ros_tools/test_ros_tools.py", line 24, in test_rosmsg_to_numpy_quaternion
    self.assertFalse(True)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 11 tests in 0.082s

FAILED (failures=1)
...
```

Is there already a way to do this?

**Comment by dirk-thomas** [comment]
No, the current implementation does not allow to pass arguments - neither from CMake nor from make: https://github.com/ros/catkin/blob/3b8a3b9607adff98ed32cfd3b6d6ea4aed647424/cmake/test/nosetests.cmake#L82

**Comment by jpanikulam** [comment]
Would osrf welcome a pull-request to add this feature?

**Comment by wjwwood** [comment]
Sure, it might be worth your time to describe how you intend to expose the arguments so we can all be on the same page before you put a lot of time into an implementation.

**Comment by dirk-thomas** [comment]
Since this was more like a question (is it currently supported) and the maintainers don't plan to implement this feature I will close the ticket.

Any pull requests for this are very welcome.
