### ISSUE TITLE
Unicode exception during `catkin_prepare_release`

### ISSUE THREAD

**Issue by fmessmer** [ros/catkin#908]
while #902 fixed this problem for `catkin_generate_changelog`, I faced a similar exception during the `catkin_prepare_release`-step of the release process

Anybody else experienced this?

**Comment by dirk-thomas** [comment]
Please provide a reproducible example.

**Comment by fmessmer** [comment]
reproducible example:

 - cd to some tmp-directory
 - `git clone https://github.com/ipa320/cob_extern.git`
 - `cd cob_extern`
 - `catkin_generate_changelog` (this works, i.e. it collects commit messages and declares them "Forthcoming")
 - `git commit -m "update changelogs" .`
 - `catkin_prepare_release` (this fails with the following exception)

```
Prepare the source repository for a release.
Repository type: git
Found packages: opengm, libqsopt, libdlib, libconcorde_tsp_solver, libphidgets, libpcan, cob_extern, libntcan
Prepare release of version '0.6.13' [Y/n]?
Trying to push to remote repository (dry run)...
To github.com:ipa320/cob_extern.git
   49973c1..83fb5b7  indigo_dev -> indigo_dev
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_prepare_release", line 393, in <module>
    main()
  File "/opt/ros/kinetic/bin/catkin_prepare_release", line 322, in main
    update_changelog_sections(missing_changelogs_but_forthcoming, new_version)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/package_version.py", line 131, in update_changelog_sections
    f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 1591: ordinal not in range(128)
```

I currently have `catkin` installed from source: https://github.com/ros/catkin/tree/1b59c751d35f91052fbf0f7ceb18c02ddde9ee5b (i.e. #902 merged)
(before, I got the same error during the `catkin_generate_changelog`-step already)

first `CHANGELOG.rst` where it fails is https://github.com/ipa320/cob_extern/blob/indigo_dev/cob_extern/CHANGELOG.rst
I then fix it manually, i.e. replace "Forthcoming" with the proper new package version, commit the local changes and re-do `catkin_prepare_release`.
Once all `CHANGELOG.rst` files have the proper package version set (manually or via `catkin_prepare_release`), `catkin_prepare_release` continues as expected pushing tags and all...

Anything else that helps debugging?

**Comment by dirk-thomas** [comment]
I just ran the sequence of commands on Kinetic with catkin version 0.7.8 and it works fine for me. Can you please provide more information like the catkin version you have installed and your locale.

**Comment by tfoote** [comment]
I can reproduce following the above using 0.7.8 on my machine from binary. I ran into this previously and manually hotpatched my system with #902 and it passed. Reinstalling the binary version caused the failure again.

```
tfoote@snowman:/tmp/cob_extern Last: [0] (0s Seconds)
$ catkin_prepare_release --no-push
Prepare the source repository for a release.
Repository type: git
Found packages: opengm, libqsopt, cob_extern, libpcan, libphidgets, libconcorde_tsp_solver, libdlib, libntcan
Prepare release of version '0.6.13' [Y/n]?
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Rename the forthcoming section of the following packages to version '0.6.13': cob_extern, libconcorde_tsp_solver, libdlib, libntcan, libpcan, libphidgets, libqsopt, opengm
Bump version of all packages from '0.6.12' to '0.6.13'
Committing the package.xml files...
[indigo_dev 9d2ebbb] 0.6.13
 16 files changed, 24 insertions(+), 24 deletions(-)
Creating tag '0.6.13'...
You can use the following commands to manually push the changes to the remote repository:
  /usr/bin/git push origin indigo_dev
  /usr/bin/git push --tags
The release of the source repository has been prepared successfully but the changes have not been pushed yet. After pushing the changes manually the next step will be 'bloom-release'.
tfoote@snowman:/tmp/cob_extern Last: [0] (1s Seconds)
$ dpkg -l | grep catkin
ii  python-catkin-pkg                           0.3.9-100                                             all          catkin package library
ii  python-catkin-pkg-modules                   0.3.9-1                                               all          catkin package library
ii  python-catkin-tools                         0.4.4-1                                               all          Command line tools for working with catkin.
ii  python3-catkin-pkg-modules                  0.3.9-1                                               all          catkin package library
ii  ros-kinetic-catkin                          0.7.8-0xenial-20171104-171232-0800                    amd64        Low-level build system macros and infrastructure for ROS.
ii  ros-lunar-catkin                            0.7.8-0xenial-20171027-164230-0800                    amd64        Low-level build system macros and infrastructure for ROS.
tfoote@snowman:/tmp/cob_extern Last: [0] (0s Seconds)
$ sudo apt-get install --reinstall ros-kinetic-catkin
[sudo] password for tfoote: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 3 not upgraded.
Need to get 114 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://packages.ros.org/ros/ubuntu xenial/main amd64 ros-kinetic-catkin amd64 0.7.8-0xenial-20171104-171232-0800 [114 kB]
Fetched 114 kB in 0s (238 kB/s)            
(Reading database ... 469161 files and directories currently installed.)
Preparing to unpack .../ros-kinetic-catkin_0.7.8-0xenial-20171104-171232-0800_amd64.deb ...
Unpacking ros-kinetic-catkin (0.7.8-0xenial-20171104-171232-0800) over (0.7.8-0xenial-20171104-171232-0800) ...
Setting up ros-kinetic-catkin (0.7.8-0xenial-20171104-171232-0800) ...
tfoote@snowman:/tmp/cob_extern Last: [0] (10s Seconds)
$ catkin_prepare_release --no-push
Prepare the source repository for a release.
Repository type: git
Found packages: opengm, libqsopt, cob_extern, libpcan, libphidgets, libconcorde_tsp_solver, libdlib, libntcan
Prepare release of version '0.6.14' [Y/n]?
Warning: the following packages do not have a changelog file or entry for version '0.6.14': cob_extern, libconcorde_tsp_solver, libdlib, libntcan, libpcan, libphidgets, libqsopt, opengm
Continue without changelogs [y/N]?y
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Rename the forthcoming section of the following packages to version '0.6.14': 
Bump version of all packages from '0.6.13' to '0.6.14'
Committing the package.xml files...
[indigo_dev 4bc3501] 0.6.14
 8 files changed, 8 insertions(+), 8 deletions(-)
Creating tag '0.6.14'...
You can use the following commands to manually push the changes to the remote repository:
  /usr/bin/git push origin indigo_dev
  /usr/bin/git push --tags
The release of the source repository has been prepared successfully but the changes have not been pushed yet. After pushing the changes manually the next step will be 'bloom-release'.
tfoote@snowman:/tmp/cob_extern Last: [0] (6s Seconds)
$ catkin_generate_changelog 
Found packages: cob_extern, libconcorde_tsp_solver, libdlib, libntcan, libpcan, libphidgets, libqsopt, opengm
Querying commit information since latest tag...
Updating forthcoming section of changelog files...
- updating 'opengm/CHANGELOG.rst'
- updating 'libconcorde_tsp_solver/CHANGELOG.rst'
- updating 'cob_extern/CHANGELOG.rst'
- updating 'libpcan/CHANGELOG.rst'
- updating 'libphidgets/CHANGELOG.rst'
- updating 'libqsopt/CHANGELOG.rst'
- updating 'libdlib/CHANGELOG.rst'
- updating 'libntcan/CHANGELOG.rst'
Done.
Please review the extracted commit messages and consolidate the changelog entries before committing the files!
tfoote@snowman:/tmp/cob_extern Last: [0] (0s Seconds)
$ git commit -m"update changelogs" -a
[indigo_dev d7ae6ed] update changelogs
 8 files changed, 24 insertions(+)
tfoote@snowman:/tmp/cob_extern Last: [0] (0s Seconds)
$ catkin_prepare_release --no-push
Prepare the source repository for a release.
Repository type: git
Found packages: opengm, libqsopt, cob_extern, libpcan, libphidgets, libconcorde_tsp_solver, libdlib, libntcan
Prepare release of version '0.6.15' [Y/n]?
Checking if working copy is clean (no staged changes, no modified files, no untracked files)...
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_prepare_release", line 393, in <module>
    main()
  File "/opt/ros/kinetic/bin/catkin_prepare_release", line 322, in main
    update_changelog_sections(missing_changelogs_but_forthcoming, new_version)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/package_version.py", line 131, in update_changelog_sections
    f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 1632: ordinal not in range(128)
```

**Comment by dirk-thomas** [comment]
> I can reproduce following the above using 0.7.8 on my machine from binary. I ran into this previously and manually hotpatched my system with #902 and it passed. Reinstalling the binary version caused the failure again.

I was trying it with the plain Debian package without applying any patches and it works for me. So I need more information what is different in your case otherwise I can't work on a fix. The same question for you as for the original author: what locale are you using when it fails?

**Comment by tfoote** [comment]
```
tfoote@snowman:~ Last: [0] (0s Seconds)
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by fmessmer** [comment]
Here is some more info on my setup:
```
( | )fxm@vinson:~$ uname -a
Linux vinson 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
( | )fxm@vinson:~$ python --version
Python 2.7.12
( | )fxm@vinson:~$ echo $ROS_DISTRO 
kinetic
( | )fxm@vinson:~$ dpkg -l | grep catkin
ii  python-catkin-pkg                            0.3.9-100                                             all          catkin package library
ii  python-catkin-pkg-modules                    0.3.9-1                                               all          catkin package library
ii  python-catkin-tools                          0.4.4-1                                               all          Command line tools for working with catkin.
ii  ros-kinetic-catkin                           0.7.8-0xenial-20171104-171232-0800                    amd64        Low-level build system macros and infrastructure for ROS.
( | )fxm@vinson:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

I initially installed `catkin` from deb, 
but after facing #901, I installed it from source (`kinetic-devel` as of https://github.com/ros/catkin/commit/1b59c751d35f91052fbf0f7ceb18c02ddde9ee5b)
(`/usr/local/lib/python2.7/dist-packages/catkin/package_version.py` contains the changes introduced in #902)

**Comment by fmessmer** [comment]
Just saw that both @tfoote and me are seeing the exception thrown from `/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/package_version.py` and not `/usr/local/lib/python2.7/dist-packages/catkin/package_version.py`, i.e. still using the debian version that does not yet contain #902...

Did I do something wrong during installation? I followed http://wiki.ros.org/catkin#Install_From_Source: 
`mkdir build && cd build && cmake ../ && make && sudo make install`

**Comment by dirk-thomas** [comment]
I don't know why the behavior is different for you two, @ipa-fxm @tfoote. As long as I am unable to reproduce the problem I won't be able to work on a patch.

If either of you could provide a pull request to address the problem I am happy to review it and check that it (continues to) work for me.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket to due inactivity. Please feel free to comment on the closed ticket with more information how to reproduce the problem or directly opening a pull request.
