### ISSUE TITLE
UnicodeEncodeError when running with --cmake-args --trace-expand

### ISSUE THREAD

**Issue by saladpanda** [ros/catkin#915]
When running `catkin_make_isolated` with `--cmake-args --trace-expand` I got the following error:

```
Traceback (most recent call last):
  File "./src/catkin/bin/../python/catkin/builder.py", line 981, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "./src/catkin/bin/../python/catkin/builder.py", line 677, in build_package
    destdir=destdir, use_ninja=use_ninja
  File "./src/catkin/bin/../python/catkin/builder.py", line 397, in build_catkin_package
    run_command_colorized(cmake_cmd, build_dir, quiet, add_env=add_env)
  File "./src/catkin/bin/../python/catkin/builder.py", line 187, in run_command_colorized
    run_command(cmd, cwd, quiet=quiet, colorize=True, add_env=add_env)
  File "./src/catkin/bin/../python/catkin/builder.py", line 238, in run_command
    out.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 124: ordinal not in range(128)
```

I don't know if it's a nice solution, but changing
https://github.com/ros/catkin/blob/dbd5cbc728396aaf17fcc5caa26c3fdb6836d48b/python/catkin/builder.py#L238
to
```
out.write(line.encode(encoding))
```
fixed the issue for me.

**Comment by dirk-thomas** [comment]
I just ran `catkin_make_isolated --cmake-args --trace-expand` on a small workspace and it worked fine for me. Please provide more information about the exact environment and steps to reproduce the problem.

**Comment by dirk-thomas** [comment]
I will close this for now due to no response. Please feel free to comment with the requested information and the issue can be reopened.
